name: G2

on:
  push:
    branches: [ master, development ]
  pull_request:
    branches: [ master, development ]

jobs:
  build:

    runs-on: ubuntu-20.04

    steps:
    - uses: actions/checkout@v3
    - uses: haskell/actions/setup@v2
      id: setup-haskell-cabal
      with:
        ghc-version: 9.4.8
        cabal-version: 3.6

    - run: cabal update
    - run: cabal configure
    - run: cabal freeze
    - uses: actions/cache@v2
      with:
        path: |
          ${{ steps.setup-haskell-cabal.outputs.cabal-store }}
          dist-newstyle
        key: cabal-${{ runner.os }}-9.4.8-${{ hashFiles('cabal.project.freeze') }}
        restore-keys: |
          cabal-${{ runner.os }}-9.4.8-

    - name: Install Z3
      uses: pavpanchekha/setup-z3@0.2.0
      with:
        version: '4.8.17'
        architecture: 'x64'
        distribution: 'glibc-2.31'
   
    - name: Getting custom base
      run: bash base_setup.sh

    - name: Install dependencies
      run: |
        cabal install --only-dependencies
        cabal build
    - name: Build
      run: cabal build

    - name: Running
      run: |
        time cabal run GGnebula -- --no-labeled-errors src\Signal.hs "morgans law 0" i
        time cabal run GGnebula -- --no-labeled-errors src\Signal.hs "morgans law 1" i
        time cabal run GGnebula -- --no-labeled-errors src\Signal.hs "morgans law 2" i
        time cabal run GGnebula -- --no-labeled-errors src\Signal.hs "morgans law 3" i
        time cabal run GGnebula -- --no-labeled-errors src\Signal.hs "morgans law 4" i
        time cabal run GGnebula -- --no-labeled-errors src\Signal.hs "morgans law 5" i